// Code generated by go-bindata.
// sources:
// data/templates/home.html
// DO NOT EDIT!

package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _dataTemplatesHomeHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x9c\x90\xc1\x4b\xc3\x30\x14\x87\xcf\xcd\x5f\xf1\xcc\xa5\x0d\x8c\x46\xaf\x5b\x3b\x10\x15\x3c\x4c\x94\xb9\x81\x22\x63\x84\xe6\xcd\x45\xd2\xa4\x26\x6f\x1b\x32\xfa\xbf\xdb\xae\x08\x2a\x9e\x3c\x3e\xf8\xbe\x1f\x1f\xaf\x38\xbb\xbe\xbf\x5a\x3c\x3f\xdc\xc0\x96\x6a\x3b\x65\x85\xd9\x04\x55\x23\xc4\x50\x95\x7c\x4b\xd4\x8c\xa5\x3c\x1e\x21\xbf\xd4\x3a\x40\xdb\xca\x80\xda\x04\xac\x88\x4f\x0b\x39\xa0\xbf\x9c\x1e\x5e\xa8\xf0\x8a\xb4\x9c\xcf\x3a\xe3\x07\x18\xab\x60\x1a\x9a\xb2\x64\xaf\x02\xec\x22\xae\xa3\x45\x6c\xa0\x84\xb4\xd7\x96\x11\x1f\x4f\x77\xdb\xa6\x8c\x25\x66\x03\xd9\x37\xa6\x83\x3e\x30\xa6\x02\x8e\x2c\x49\xc8\x37\x2f\xe7\xab\x1c\xf7\xca\x66\xe9\xba\xec\xcf\x8b\xd5\xe4\x60\x68\x9b\x39\x3c\xc0\xd3\xdd\xec\xb6\x6b\x9f\xe3\xfb\x0e\x23\x09\xdf\xa0\xcb\x78\x97\xc4\x47\x5c\x9e\xe6\xf8\x68\xa3\x6c\x44\x31\x8a\xe8\x74\x26\x26\xeb\xdc\xfa\x4a\x91\xf1\xae\xe4\x6f\x6a\xaf\x86\xd0\xb1\xb2\x18\x28\xd3\xbe\xda\xd5\xe8\x28\xd7\xbe\x56\xc6\x09\x9e\x8a\x09\x4b\x5a\xc0\x6e\xa1\xaf\x81\xbf\x6b\x06\xf9\x7f\xdb\xac\x90\x5f\xbf\xfa\x0c\x00\x00\xff\xff\xf0\x1c\x2a\x80\xa2\x01\x00\x00")

func dataTemplatesHomeHtmlBytes() ([]byte, error) {
	return bindataRead(
		_dataTemplatesHomeHtml,
		"data/templates/home.html",
	)
}

func dataTemplatesHomeHtml() (*asset, error) {
	bytes, err := dataTemplatesHomeHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/templates/home.html", size: 418, mode: os.FileMode(420), modTime: time.Unix(1455062446, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"data/templates/home.html": dataTemplatesHomeHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"data": &bintree{nil, map[string]*bintree{
		"templates": &bintree{nil, map[string]*bintree{
			"home.html": &bintree{dataTemplatesHomeHtml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

